import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75
blur = true
# 边缘空白
decorations = "Buttonless"
dynamic_padding = false
padding = { x = 10, y = 15 }

[shell]
program = "/usr/local/bin/zsh-5.9"
args = ["-l", "-c", "tmux attch || tmux"]


[font]
size = 16.0
builtin_box_drawing = true

[font.bold]
family = "Symbols Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Symbols Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "Symbols Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(https|http):[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Select"
hyperlinks = true
post_processing = true
regex = "(file|git|ssh|ftp|ipfs|ipns|magnet|mailto):[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
    # Vi Mode

    # Search Mode

    # Tmuxe
    { key = "T", mods = "Command", chars = "\u0001c" }, # new tab with default shell

]
