import = ["~/.config/alacritty/dracula.toml"]

[font]
size = 16.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 5

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[font.offset]
x = 0
y = 10

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(https|http):[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Select"
hyperlinks = true
post_processing = true
regex = "(file|git|ssh|ftp|ipfs|ipns|magnet|mailto):[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
    { key = "I", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineUp" },
    { key = "I", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineUp" },
    { key = "I", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineUp" },
    { key = "I", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineUp" },
    { key = "I", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineUp" },
    { key = "K", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineDown" },
    { key = "K", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineDown" },
    { key = "K", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineDown" },
    { key = "K", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineDown" },
    { key = "K", mods = "Control", mode = "~Vi|~Alt", action = "ScrollLineDown" },
    { key = "J", mods = "Control", mode = "~Vi|~Alt", chars = "\"\\x01\"" },
    { key = "L", mods = "Control", mode = "~Vi|~Alt", chars = "\"\\x05\"" },
    { key = "Back", mods = "Alt", action = "None" },
    { key = "Back", mods = "Control", chars = "\"\\x15\"" },

    # Vi Mode
    { key = "Space", mods = "Control", action = "ToggleViMode" },
    { key = "Escape", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "I", mode = "Vi|~Search", action = "Up" },
    { key = "I", mode = "Vi|~Search", action = "CenterAroundViCursor" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "Up" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "Up" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "Up" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "Up" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "Up" },
    { key = "I", mods = "Shift", mode = "Vi|~Search", action = "CenterAroundViCursor" },
    { key = "K", mode = "Vi|~Search", action = "Down" },
    { key = "K", mode = "Vi|~Search", action = "CenterAroundViCursor" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "Down" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "Down" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "Down" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "Down" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "Down" },
    { key = "K", mods = "Shift", mode = "Vi|~Search", action = "CenterAroundViCursor" },
    { key = "J", mode = "Vi|~Search", action = "Left" },
    { key = "J", mods = "Shift", mode = "Vi|~Search", action = "First" },
    { key = "L", mode = "Vi|~Search", action = "Right" },
    { key = "L", mods = "Shift", mode = "Vi|~Search", action = "Last" },
    { key = "G", mode = "Vi|~Search", action = "ScrollToTop" },
    { key = "G", mods = "Shift", mode = "Vi|~Search", action = "ScrollToBottom" },
    { key = "Y", mode = "Vi|~Search", action = "Copy" },
    { key = "Y", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "V", mode = "Vi|~Search", action = "ToggleNormalSelection" },
    { key = "V", mods = "Shift", mode = "Vi|~Search", action = "ToggleLineSelection" },
    { key = "V", mods = "Control", mode = "Vi|~Search", action = "ToggleBlockSelection" },
    { key = "Return", mode = "Vi|~Search", action = "Open" },
    { key = "B", mode = "Vi|~Search", action = "SemanticLeft" },
    { key = "B", mods = "Shift", mode = "Vi|~Search", action = "WordLeft" },
    { key = "W", mode = "Vi|~Search", action = "SemanticRight" },
    { key = "W", mods = "Shift", mode = "Vi|~Search", action = "WordRight" },
    { key = "E", mode = "Vi|~Search", action = "SemanticRightEnd" },
    { key = "E", mods = "Shift", mode = "Vi|~Search", action = "WordRightEnd" },
    { key = "Slash", mode = "Vi|~Search", action = "SearchForward" },
    { key = "Slash", mods = "Shift", mode = "Vi|~Search", action = "SearchBackward" },
    { key = "N", mode = "Vi|~Search", action = "SearchNext" },
    { key = "N", mods = "Shift", mode = "Vi|~Search", action = "SearchPrevious" },

    # Search Mode
    { key = "Escape", mode = "Search", action = "SearchCancel" },
    { key = "Return", mode = "Search|Vi", action = "SearchConfirm" },
    { key = "Return", mode = "Search|~Vi", action = "SearchFocusNext" },
    { key = "Return", mods = "Shift", mode = "Search|~Vi", action = "SearchFocusPrevious" },
    { key = "Back", mods = "Control", mode = "Search", action = "SearchClear" },
    { key = "Back", mods = "Command", mode = "Search", action = "SearchDeleteWord" },
    { key = "I", mods = "Command", mode = "Search", action = "SearchHistoryPrevious" },
    { key = "K", mods = "Command", mode = "Search", action = "SearchHistoryNext" },

    # macOS only
    { key = "R", mods = "Command", mode = "~Vi|~Search", chars = "\"\\x0c\"" },
    { key = "R", mods = "Command", mode = "~Vi|~Search", action = "ClearHistory" },
    { key = "Key0", mods = "Command", action = "ResetFontSize" },
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    { key = "V", mods = "Command", action = "Paste" },
    { key = "C", mods = "Command", action = "Copy" },
    { key = "C", mods = "Command", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "H", mods = "Command", action = "Hide" },
    { key = "H", mods = "Command|Alt", action = "HideOtherApplications" },
    { key = "M", mods = "Command", action = "Minimize" },
    { key = "Q", mods = "Command", action = "Quit" },
    { key = "W", mods = "Command", action = "Quit" },
    { key = "N", mods = "Command", action = "CreateNewWindow" },
    { key = "I", mods = "Command", mode = "~Vi|~Alt", chars = "\"\\x1b[A\"" },
    { key = "K", mods = "Command", mode = "~Vi|~Alt", chars = "\"\\x1b[B\"" },
    { key = "J", mods = "Command", mode = "~Vi|~Alt", chars = "\"\\x1bb\"" },
    { key = "L", mods = "Command", mode = "~Vi|~Alt", chars = "\"\\x1bf\"" },
    { key = "Back", mods = "Command", mode = "~Vi|~Alt", chars = "\"\\x17\"" },
    { key = "Return", mods = "Command", action = "ToggleFullscreen" },
]
