-- https://www.nerdfonts.com/cheat-sheet

vim.g.icons = {

	Git = {
		Branch = " ",
		Staged = " ",
		Unstaged = "󰄱 ",
		Untracked = " ",
		Conflicted = " ",
		Ignored = " ", -- 
		Rename = " ",
		Add = " ",
		Delete = " ",
		Modify = " ",
		Merge = " ",
		Rebase = " ",
		Push = "↑",
		Pull = " ",
		Tag = " ",
		Head = "",
		Remote = "󰁕",
		Stash = " ",
		Gutter = "✎ ",
		Blame = " ",
		Log = " ",
		Commit = " ",
		Bisect = " ",
		Reset = " ",
		Checkout = " ",
		BranchDelete = " ",
		BranchCreate = " ",
		BranchMove = " ",
		BranchMerge = " ",
		BranchCompare = " ",
		BranchFork = " ",
		BranchFlag = " ",
		BranchLock = " ",
		BranchUnlock = " ",
		BranchRename = " ",
		BranchPush = " ",
		BranchPull = " ",
		BranchMergeConflict = " ",
		BranchRemote = " ",
	},
	Diagnostic = {
		Error = " ",
		Warning = " ",
		Info = " ",
		Hint = " ",
	},
	File = {
		Directory = " ",
		File = " ",
		Symlink = " ",
		Socket = " ",
		Pipe = " ",
		BlockDevice = " ",
		CharDevice = " ",
		Special = " ",
		Modify = " ",
	},
	Folder = {
		open = " ",
		closed = " ",
		empty = " ",
		empty_open = " ",
		symlink = " ",
		symlink_open = " ",
	},
	Overseer = {
		Canceled = " ",
		Failure = "󰅚 ",
		Success = "󰄴 ",
		Running = "󰑮 ",
	},
	Telescope = {
		Prefix = " ",
		Care = " ",
		MultiIcon = " ",
	},
}
