[manager]
show_hidden = true

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'open "$@"', desc = "Open" }]

[open]
# append_rules = [{ name = "*", use = "zed" }]

[plugin]
prepend_previewers = [{ name = "*.md", run = "glow" }]
prepend_fetchers = [
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" },
]
