require("modules.monitors")
require("modules.keymap")
require("modules.workspace")
require("modules.envs")
require("modules.input")
require("modules.misc")
require("modules.group")
require("modules.general")
require("modules.animations")
require("modules.window-rule")

require("shell.noctalia")
