# zmodload zsh/zprof

. "$HOME/.cargo/env"

export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

autoload -Uz add-zsh-hook

initialized_envs=()

_load_goenv() {
    if [[ ! " ${initialized_envs[@]} " =~ " goenv " ]]; then
        export GOENV_ROOT="$HOME/.config/env/goenv"
        export PATH="$GOENV_ROOT/bin:$PATH"
        eval "$(goenv init -)"

        export GOPATH=/Volumes/Code/Projects/golang
        export PATH="$PATH:$GOPATH:$GOPATH/bin"
        export PATH="$GOROOT/bin:$PATH"

        export GOPROXY=https://goproxy.cn,direct
        export GOSUMDB=sum.golang.google.cn
        export GOENV_DISABLE_GOPATH=1

        initialized_envs+=("goenv")
    fi
}

_load_luaenv() {
    if [[ ! " ${initialized_envs[@]} " =~ " luaenv " ]]; then
        export LUAENV_ROOT="$HOME/.config/env/luaenv"
        command -v luaenv >/dev/null || export PATH="$LUAENV_ROOT/bin:$PATH"
        eval "$(luaenv init -)"

        export MACOSX_DEPLOYMENT_TARGET=12.7
        # export LUAENV_VERSION=5.2.4

        initialized_envs+=("luaenv")
    fi
}

_load_nodenv() {
    if [[ ! " ${initialized_envs[@]} " =~ " nodenv " ]]; then
        export NODENV_ROOT="$HOME/.config/env/nodenv"
        export PATH="$NODENV_ROOT/bin:$PATH"
        eval "$(nodenv init - zsh)"
        
        initialized_envs+=("nodenv")
    fi
}

_load_pyenv() {
    if [[ ! " ${initialized_envs[@]} " =~ " pyenv " ]]; then
        export PYENV_ROOT="$HOME/.config/env/pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        
        initialized_envs+=("pyenv")
    fi
}

_initialize_envs() {
    _load_goenv
    _load_luaenv
    _load_nodenv
    _load_pyenv
}

add-zsh-hook precmd _initialize_envs

# zprof
