# zmodload zsh/zprof

# rust
if [[ -d "${HOME}/.cargo/bin" ]]; then
  export PATH="${HOME}/.cargo/bin:${PATH}"
fi

export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

autoload -U compinit
compinit


_lazyload_add_command() {
    eval "$1() { \
        unfunction $1; \
        _sukka_lazyload_command_$1; \
        $1 \$@; \
    }"
}

_lazyload_add_completion() {
    local comp_name="_sukka_lazyload__compfunc_$1"
    eval "${comp_name}() { \
        compdef -d $1; \
        _sukka_lazyload_completion_$1; \
    }"
    compdef $comp_name $1
}


# GoENV
export GOENV_ROOT="$HOME/.config/env/goenv"
export PATH="$GOENV_ROOT/bin:$GOENV_ROOT/shims:$PATH"

export PATH="$PATH:$GOPATH:$GOPATH/bin"
export PATH="$GOROOT/bin:$PATH"

export GOPROXY=https://goproxy.cn,direct
export GOSUMDB=sum.golang.google.cn
export GOENV_DISABLE_GOPATH=1

if (( $+commands[goenv] )) &>/dev/null; then
    _sukka_lazyload_command_goenv() {
        eval "$(goenv init -)"
    }

    _sukka_lazyload_completion_goenv() {
        source "$GOENV_ROOT/completions/goenv.zsh"
    }

    _lazyload_add_command goenv
    _lazyload_add_completion goenv
fi


export LUAENV_ROOT="$HOME/.config/env/luaenv"
export PATH="$LUAENV_ROOT/bin:$LUAENV_ROOT/shims:$PATH"
if (( $+commands[luaenv] )) &>/dev/null; then
    _sukka_lazyload_command_luaenv() {
        eval "$(luaenv init -)"
    }

    _sukka_lazyload_completion_luaenv (){
        source "$LUAENV_ROOT/completions/luaenv.zsh"
    }

    _lazyload_add_command luaenv
    _lazyload_add_completion luaenv
fi

export NODENV_ROOT="$HOME/.config/env/nodenv"
export PATH="$NODENV_ROOT/bin:$NODENV_ROOT/shims:$PATH"
if (( $+commands[nodenv] )) &>/dev/null; then
    _sukka_lazyload_command_nodenv() {
        eval "$(nodenv init - zsh)"
    }
    
    _sukka_lazyload_completion_nodenv() {
        source "$NODENV_ROOT/completions/nodenv.zsh"
    }

    _lazyload_add_command nodenv
    _lazyload_add_completion nodenv
fi

## Lazyload pyenv
export PYENV_ROOT="$HOME/.config/env/pyenv"
export PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}" # pyenv init --path
if (( $+commands[pyenv] )) &>/dev/null; then
    _sukka_lazyload_command_pyenv() {
        eval "$(command pyenv init -)"
        eval "$(command pyenv virtualenv-init -)"

    }
    _lazyload_add_command pyenv

    _sukka_lazyload_completion_pyenv() {
        source "${PYENV_ROOT}/completions/pyenv.zsh"
    }
    _lazyload_add_completion pyenv

    export PYENV_ROOT="$HOME/.config/env/pyenv"

fi

# zprof
