
# golang
export GOENV_ROOT="$HOME/.config/env/goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"

export GOPATH=/Volumes/Code/Projects/golang
export PATH="$PATH:$GOPATH:$GOPATH/bin"
export PATH="$GOROOT/bin:$PATH"

export GOPROXY=https://goproxy.cn,direct
export GOSUMDB=sum.golang.google.cn
export GOENV_DISABLE_GOPATH=1


# lua
export LUAENV_ROOT="$HOME/.config/env/luaenv"

command -v luaenv >/dev/null || export PATH="$LUAENV_ROOT/bin:$PATH"
eval "$(luaenv init -)"

export MACOSX_DEPLOYMENT_TARGET=12.7
# export LUAENV_VERSION=5.2.4


# node
export NODENV_ROOT="$HOME/.config/env/nodenv"
export PATH="$NODENV_ROOT/bin:$PATH"
eval "$(nodenv init - zsh)"


# pyenv
export PYENV_ROOT="$HOME/.config/env/pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export CPPFLAGS="-I$(brew --prefix zlib)/include"
export PATH=$PATH:/usr/local/opt/tcl-tk/bin
# alias pyenv="env PYTHON_CONFIGURE_OPTS=--enable-shared pyenv"
