if [[ $- != *i* ]]; then
    return
fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

zinit snippet OMZL::git.zsh
zinit light romkatv/zsh-defer
zsh-defer zinit light-mode for zdharma-continuum/zinit-annex-bin-gem-node
zsh-defer zinit light zsh-users/zsh-completions
# zsh-defer zinit light zinit-zsh/z-a-meta-plugins

# autoload -U compinit
# compinit

# homebrew
# brew why
function brew() {
    if [[ $1 == "why" ]]; then
        brew uses --installed $2
    else
        command brew "$@"
    fi
}

zinit snippet $HOME/.config/zsh/init.zsh
export PATH="/usr/local/sbin:$PATH"

